version: '3'

services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_HOST: database
      DB_USER: rails-api
      DB_PASSWORD: rails-api
    depends_on:
      - database

  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rails-api
      POSTGRES_PASSWORD: rails-api
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
