name: Continuous integration

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: rails-api
          POSTGRES_PASSWORD: rails-api

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: RSpec
        env:
          DB_HOST: localhost
          DB_USER: rails-api
          DB_PASSWORD: rails-api
          RAILS_ENV: test
        run: |
          bundle exec rake db:create db:schema:load
          bundle exec rspec

      - name: Lint with RuboCop
        run: bundle exec rubocop --parallel
